version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
