FetchContent_Declare(webview URL https://api.nuget.org/v3-flatcontainer/microsoft.web.webview2/1.0.4191.47/microsoft.web.webview2.1.0.4191.47.nupkg
  URL_HASH SHA256=f492bbf547d0da329553b6727435b677579b1e9f91cc9e4a1ad029366d5f23d0)
FetchContent_Declare(epubjs URL https://registry.npmjs.org/epubjs/-/epubjs-0.3.93.tgz
  URL_HASH SHA256=180b33059ca15e2b4f129eb7fef6cae0bf6005c02af5194d13e5cb48378d538f)
FetchContent_Declare(jszip URL https://registry.npmjs.org/jszip/-/jszip-3.10.1.tgz
  URL_HASH SHA256=5117f4a2a645aeb307bf3b829c575ad58135cc97e75291e594532ab5b5b21b23)
FetchContent_Declare(docxpreview URL https://registry.npmjs.org/docx-preview/-/docx-preview-0.4.0.tgz
  URL_HASH SHA256=94c336d6a1ea69d188bc95bfb4c6de55ea6414270477359ddda557d1a5bea447)
FetchContent_MakeAvailable(webview epubjs jszip docxpreview)
configure_file(src/reader_assets.rc.in generated/reader_assets.rc @ONLY)
add_library(books_reader src/reader.cpp src/docx_text.cpp)
include(cmake/doc.cmake)
add_dependencies(books_reader VolturaBooksDoc)
add_executable(VolturaBooksReader WIN32 src/rtf_helper.cpp)
target_link_options(VolturaBooksReader PRIVATE /MANIFEST:EMBED /MANIFESTINPUT:${CMAKE_CURRENT_SOURCE_DIR}/src/app.manifest)
target_include_directories(VolturaBooksReader PRIVATE ${webview_SOURCE_DIR}/build/native/include)
target_link_libraries(VolturaBooksReader PRIVATE ${webview_SOURCE_DIR}/build/native/x64/WebView2LoaderStatic.lib version)
target_compile_definitions(VolturaBooksReader PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
target_compile_options(VolturaBooksReader PRIVATE /W4 /utf-8 /permissive-)
target_link_libraries(VolturaBooksReader PRIVATE ole32 uuid gdi32 user32 windowscodecs shlwapi shell32)
install(TARGETS VolturaBooksReader RUNTIME DESTINATION .)
add_dependencies(books_reader VolturaBooksReader)
target_include_directories(books_reader PUBLIC src PRIVATE ${webview_SOURCE_DIR}/build/native/include)
target_link_libraries(books_reader PUBLIC books_cover books_theme PRIVATE ${webview_SOURCE_DIR}/build/native/x64/WebView2LoaderStatic.lib version)
target_compile_options(books_reader PRIVATE /W4 /utf-8 /permissive-)
# Resource objects must be linked into each executable, not hidden in a static library.
target_sources(books_reader INTERFACE ${CMAKE_CURRENT_BINARY_DIR}/generated/reader_assets.rc)
file(READ ${epubjs_SOURCE_DIR}/license EPUB_NOTICE)
file(READ ${jszip_SOURCE_DIR}/LICENSE.markdown JSZIP_NOTICE)
string(FIND "${JSZIP_NOTICE}" "GPL version 3" JSZIP_GPL_START)
string(SUBSTRING "${JSZIP_NOTICE}" 0 ${JSZIP_GPL_START} JSZIP_NOTICE)
file(READ ${webview_SOURCE_DIR}/LICENSE.txt WEBVIEW_NOTICE)
file(READ ${CMAKE_CURRENT_SOURCE_DIR}/src/reader-third-party-notices.txt READER_NOTICES)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/reader-third-party-notices.txt)
file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/THIRD-PARTY-NOTICES.txt "\nEPUB.js\n${EPUB_NOTICE}\nJSZip (used under MIT)\n${JSZIP_NOTICE}\nWebView2 SDK\n${WEBVIEW_NOTICE}\n${READER_NOTICES}\n")
foreach(target VolturaBooks browser_preview browser_tests drop_preview queue_tests cover_preview settings_preview)
  if(TARGET ${target})
    target_link_libraries(${target} PRIVATE books_reader)
    # TaskDialogIndirect (reader fallback) requires common-controls v6, including
    # in test executables that previously ran without an application manifest.
    target_link_options(${target} PRIVATE /MANIFEST:EMBED /MANIFESTINPUT:${CMAKE_CURRENT_SOURCE_DIR}/src/app.manifest)
  endif()
endforeach()
if(BOOKS_BUILD_TESTS)
  add_executable(reader_native_loading_tests tests/reader_native_loading_tests.cpp src/app.rc)
  target_include_directories(reader_native_loading_tests PRIVATE ${webview_SOURCE_DIR}/build/native/include)
  target_link_libraries(reader_native_loading_tests PRIVATE books_reader ${webview_SOURCE_DIR}/build/native/x64/WebView2LoaderStatic.lib version)
  target_compile_options(reader_native_loading_tests PRIVATE /utf-8)
  target_link_options(reader_native_loading_tests PRIVATE /MANIFEST:EMBED /MANIFESTINPUT:${CMAKE_CURRENT_SOURCE_DIR}/src/app.manifest)
  find_program(BOOKS_NODE node)
  if(BOOKS_NODE)
    add_test(NAME reader_bridge COMMAND "${BOOKS_NODE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/reader_bridge_tests.js" "${CMAKE_CURRENT_SOURCE_DIR}/src/reader.html")
    set_tests_properties(reader_bridge PROPERTIES TIMEOUT 10)
  endif()
  add_executable(docx_text_tests tests/docx_text_tests.cpp src/docx_text.cpp)
  target_link_libraries(docx_text_tests PRIVATE books_cover)
  target_compile_options(docx_text_tests PRIVATE /utf-8)
  add_executable(reader_tests tests/reader_tests.cpp src/app.rc)
  target_include_directories(reader_tests PRIVATE ${webview_SOURCE_DIR}/build/native/include)
  target_link_libraries(reader_tests PRIVATE books_reader books_core ${webview_SOURCE_DIR}/build/native/x64/WebView2LoaderStatic.lib version)
  target_compile_options(reader_tests PRIVATE /utf-8)
  target_link_options(reader_tests PRIVATE /MANIFEST:EMBED /MANIFESTINPUT:${CMAKE_CURRENT_SOURCE_DIR}/src/app.manifest)
  find_package(Python3 QUIET COMPONENTS Interpreter)
  if(Python3_Interpreter_FOUND)
    add_test(NAME reader_native_loading COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/reader_native_loading_fixture.py $<TARGET_FILE:reader_native_loading_tests>)
    set_tests_properties(reader_native_loading PROPERTIES TIMEOUT 60)
    add_test(NAME docx_text COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/docx_text_fixture.py $<TARGET_FILE:docx_text_tests>)
    set_tests_properties(docx_text PROPERTIES TIMEOUT 40)
    add_test(NAME rtf_fit COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/rtf_fit_fixture.py $<TARGET_FILE:VolturaBooksReader>)
    set_tests_properties(rtf_fit PROPERTIES TIMEOUT 30)
    add_test(NAME reader COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/reader_fixture.py $<TARGET_FILE:reader_tests>)
    set_tests_properties(reader PROPERTIES TIMEOUT 180)
  endif()
endif()

file(READ ${docxpreview_SOURCE_DIR}/LICENSE DOCX_NOTICE)
file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/THIRD-PARTY-NOTICES.txt "\ndocx-preview 0.4.0\nCopyright Volodymyr Baydalka\n${DOCX_NOTICE}\n")
